spring:
  application:
    name: configserver
  profiles:
    active: git,test,qa,prod
  cloud:
    config:
      server:
        git:
          uri: git@github.com:kuanhc96/freelance-configfiles.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
          ignore-local-ssh-settings: true
#         prvk: | <pvrk>
  rabbitmq:
    host: rabbit
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
server:
  port: 8071
encrypt:
  key: abcdefghijklmnop