spring:
  application:
    name: configserver
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:git,test}
  cloud:
    bus:
      enabled: ${SPRING_CLOUD_BUS_ENABLED:true}
    config:
      server:
        git:
          uri: git@github.com:kuanhc96/freelance-configfiles.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
          ignore-local-ssh-settings: true
          private-key: ${PRIVATE_KEY}
  rabbitmq:
    host: rabbit
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
    rabbit:
      enabled: ${MANAGEMENT_HEALTH_RABBIT_ENABLED:true}
  endpoint:
    health:
      probes:
        enabled: true
server:
  port: 8071
encrypt:
  key: ${ENCRYPT_KEY}